let data = {
    // <-------------------------------------------------------------------Computer---------------------------------------------------------------->

    collage_name: "L. E. Collage",
    department_data: [
        {
            department: "Computer",
            dep_head: "M.S. Dhoni",
            year: [
                {
                    year: "First",
                    year_head: "Devendra Thakor",
                    student_data: [
                        {
                            id: "2022_1",
                            student_name: "Vivek Bajaj",
                            email_id: "vevekbajaj@gmail.com",
                            contact_number: "9879870001",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "76",
                        },
                        {
                            id: "2022_2",
                            student_name: "Shalini Patel",
                            email_id: "pshalini@gmail.com",
                            contact_number: "9879870002",
                            gender: "Female",
                            admission_year: "2022",
                            merit_12th: "85",
                        },
                        {
                            id: "2022_3",
                            student_name: "Kevin jadeja",
                            email_id: "kevin@gmail.com",
                            contact_number: "9879870003",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "87",
                        },
                        {
                            id: "2022_4",
                            student_name: "Harsh Dhorajiya",
                            email_id: "Harsh22@gmail.com",
                            contact_number: "9879870004",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "83",
                        },
                        {
                            id: "",
                            student_name: "Vishal Gajera",
                            email_id: "",
                            contact_number: "9835540004",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "93",
                        },
                    ],
                },

                // <-------------------------------------------------------------second year---------------------------------------------------------->
                {
                    year: "Second",
                    year_head: "Rachana Patel",
                    student_data: [
                        {
                            id: "2021_1",
                            student_name: "Divayesh Ranpara",
                            email_id: "dr@gmail.com",
                            contact_number: "9879870005",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "78",
                        },
                        {
                            id: "",
                            student_name: "Yagnik Devani",
                            email_id: "",
                            contact_number: "9879870001",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "88",
                        }, {
                            id: "",
                            student_name: "Ronak Koladiya",
                            email_id: "",
                            contact_number: "9879870008",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "80",
                        },
                        {
                            id: "2022_0_2",
                            student_name: "Krunal Mehata",
                            email_id: "Krunal23@gmail.com",
                            contact_number: "9879870006",
                            gender: "Male",
                            admission_year: "2022",
                            merit_diploma: "88",
                        },
                        {
                            id: "2022_0_4",
                            student_name: "Shubham Khunt",
                            email_id: "shubhu7@gmail.com",
                            contact_number: "9879870007",
                            gender: "Male",
                            admission_year: "2022",
                            merit_diploma: "67",
                        },
                        {
                            id: "",
                            student_name: "Bhargav Gajera",
                            email_id: "",
                            contact_number: "9835540004",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "93",
                        },
                        {
                            id: "2021_2",
                            student_name: "Ashwin Patel",
                            email_id: "apatel@gmail.com",
                            contact_number: "9879870008",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "77",
                        },
                    ],
                },

                // <-------------------------------------------------------------third year----------------------------------------------------------->
                {
                    year: "Third",
                    year_head: "Niyanta Desai",
                    student_data: [
                        {
                            id: "2021_0_1",
                            student_name: "Chitranjan Rama",
                            email_id: "c.r@gmail.com",
                            contact_number: "9879870001",
                            gender: "Male",
                            admission_year: "2021",
                            merit_diploma: "72",
                        },
                        {
                            id: "2020_2",
                            student_name: "Nupur Parmer",
                            email_id: "np@gmail.com",
                            contact_number: "9879870010",
                            gender: "Female",
                            admission_year: "2020",
                            merit_12th: "77",
                        },
                        {
                            id: "2020_3",
                            student_name: "Sameera Rai",
                            email_id: "sameera@gmail.com",
                            contact_number: "9879870011",
                            gender: "Female",
                            admission_year: "2020",
                            merit_12th: "88",
                        },
                        {
                            id: "2020_4",
                            student_name: "Prabhat Goda",
                            email_id: "pg@gmail.com",
                            contact_number: "9879870012",
                            gender: "Male",
                            admission_year: "2020",
                            merit_12th: "65",
                        },
                        {
                            id: "2021_0_2",
                            student_name: "Vaishali Bhatt",
                            email_id: "Vaishali_bhatt@gmail.com",
                            contact_number: "98798734011",
                            gender: "Female",
                            admission_year: "2021",
                            merit_diploma: "74",
                        },
                        {
                            id: "",
                            student_name: "Mitesh Dudhat",
                            email_id: "",
                            contact_number: "98355434655",
                            gender: "Male",
                            admission_year: "2020",
                            merit_12th: "93",
                        },
                        {
                            id: "",
                            student_name: "Pinal Patel",
                            email_id: "",
                            contact_number: "9978021537",
                            gender: "Female",
                            admission_year: "2021",
                            merit_diploma: "93",
                        },
                    ],
                },

                // <--------------------------------------------------------------fourth Year---------------------------------------------------------->
                {
                    year: "Fourth",
                    year_head: "D.S. Patil",
                    student_data: [
                        {
                            id: "2019_1",
                            student_name: "Nancy Patel",
                            email_id: "nancy@gmail.com",
                            contact_number: "9879870013",
                            gender: "Female",
                            admission_year: "2019",
                            merit_12th: "77",
                        },
                        {
                            id: "2019_2",
                            student_name: "Sankalp Desai",
                            email_id: "sankalp",
                            contact_number: "9879870014",
                            gender: "Male",
                            admission_year: "2019",
                            merit_12th: "75",
                        },
                        {
                            id: "2019_3",
                            student_name: "Sudheer Chouhan",
                            email_id: "sc@gmail.com",
                            contact_number: "9879870001",
                            gender: "Male",
                            admission_year: "2019",
                            merit_12th: "57",
                        },
                        {
                            id: "2019_4",
                            student_name: "Niyati Chawada",
                            email_id: "niyati@gmail.com",
                            contact_number: "9879870016",
                            gender: "Female",
                            admission_year: "2019",
                            merit_12th: "89",
                        },
                        {
                            id: "",
                            student_name: "Megha Chawada",
                            email_id: "",
                            contact_number: "9893570016",
                            gender: "Female",
                            admission_year: "2020",
                            merit_diploma: "90",
                        },
                        {
                            id: "",
                            student_name: "Jyoti Chavda",
                            email_id: '',
                            contact_number: "9889870016",
                            gender: "Female",
                            admission_year: "2019",
                            merit_12th: "79",
                        },
                    ],
                },

                // <--------------------------------------------------------------pass year------------------------------------------------------------>
                {
                    year: "Pass Out",
                    year_head: "Bhavik Patel",
                    student_data: [
                        {
                            id: "2018_1",
                            student_name: "Rutu Patel",
                            email_id: "rutu@gmail.com",
                            contact_number: "9879870033",
                            gender: "Female",
                            admission_year: "2018",
                            merit_12th: "68",
                        },
                        {
                            id: "2018_2",
                            student_name: "Charmi Dhudhat",
                            email_id: "charmi@gmail.com",
                            contact_number: "9879870034",
                            gender: "Female",
                            admission_year: "2018",
                            merit_12th: "87",
                        },
                        {
                            id: "2018_3",
                            student_name: "Savi Dravid",
                            email_id: "savi@gmail.com",
                            contact_number: "9879870035",
                            gender: "Feamle",
                            admission_year: "2018",
                            merit_12th: "91",
                        },
                        {
                            id: "2018_4",
                            student_name: "Savi patel",
                            email_id: "savi_patel@gmail.com",
                            contact_number: "98723470035",
                            gender: "Feamle",
                            admission_year: "2018",
                            merit_12th: "80",
                        },
                        {
                            id: "2018_5",
                            student_name: "raxita vaghasiya",
                            email_id: "raxita_vaghasiya@gmail.com",
                            contact_number: "987343470035",
                            gender: "Feamle",
                            admission_year: "2018",
                            merit_12th: "86",
                        },
                        {
                            id: "",
                            student_name: "Dhyey Sharma",
                            email_id: "",
                            contact_number: "8141652472",
                            gender: "Male",
                            admission_year: "2018",
                            merit_12th: "85",
                        },
                        {
                            id: "",
                            student_name: "Shrushti Miyani",
                            email_id: "",
                            contact_number: "8141652472",
                            gender: "Feamle",
                            admission_year: "2018",
                            merit_12th: "86",
                        },
                        {
                            id: "",
                            student_name: "Darshan chopda",
                            email_id: "",
                            contact_number: "8148652472",
                            gender: "Male",
                            admission_year: "2018",
                            merit_12th: "65",
                        },
                        {
                            id: "2018_6",
                            student_name: "Ishan Vekariya",
                            email_id: "ishan@gmail.com",
                            contact_number: "9879870036",
                            gender: "Male",
                            admission_year: "2018",
                            merit_12th: "78",
                        },
                    ],
                },
            ],
        },

        // <-----------------------------------------------------------------automobile------------------------------------------------------------>

        {
            department: "Automobile",
            dep_head: "Sachin Tendulkar",
            year: [
                {
                    year: "First",
                    year_head: "Akhilsh Yadav",
                    student_data: [
                        {
                            id: "2022_1",
                            student_name: "Sanket desai",
                            email_id: "sanket@gmail.com",
                            contact_number: "9879870017",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "67",
                        },
                        {
                            id: "2022_2",
                            student_name: "Ram Taneja",
                            email_id: "rt@gmail.com",
                            contact_number: "9879870018",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "76",
                        },
                        {
                            id: "2022_3",
                            student_name: "Vishakha Dhameliya",
                            email_id: "vd@gmail.com",
                            contact_number: "9879870017",
                            gender: "Feamle",
                            admission_year: "2022",
                            merit_12th: "96",
                        },
                        {
                            id: "2022_4",
                            student_name: "Vanshika Tandel",
                            email_id: "vt@gmail.com",
                            contact_number: "9879870034",
                            gender: "Female",
                            admission_year: "2022",
                            merit_12th: "76",
                        },
                    ],
                },
                // <--------------------------------------------------------------second year---------------------------------------------------------------------->
                {
                    year: "Second",
                    year_head: "V.K Shah",
                    student_data: [
                        {
                            id: "2022_0_1",
                            student_name: "Parth Patel",
                            email_id: "pp@gmail.com",
                            contact_number: "9879870021",
                            gender: "Male",
                            admission_year: "2022",
                            merit_diploma: "80",
                        },
                        {
                            id: "2021_2",
                            student_name: "Mahi Vaghani",
                            email_id: "mv@gmail.com",
                            contact_number: "9879870022",
                            gender: "Female",
                            admission_year: "2021",
                            merit_12th: "65",
                        },
                        {
                            id: "2021_3",
                            student_name: "Sakshi Bajaj",
                            email_id: "sb@gmail.com",
                            contact_number: "9879870023",
                            gender: "Female",
                            admission_year: "2021",
                            merit_12th: "87",
                        },
                        {
                            id: "2021_4",
                            student_name: "Naveen Shah",
                            email_id: "ns@gmail.com",
                            contact_number: "9879870024",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "56",
                        },
                        {
                            id: "2021_5",
                            student_name: "vairagi dave",
                            email_id: "vairagi_dave@gmail.com",
                            contact_number: "9879870034",
                            gender: "Female",
                            admission_year: "2021",
                            merit_12th: "93",
                        },
                        {
                            id: "",
                            student_name: "Shubham Chauhan",
                            email_id: "",
                            contact_number: "54872165478",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "85",
                        },
                        {
                            id: "",
                            student_name: "Nirav Loriya",
                            email_id: "",
                            contact_number: "9879870017",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "85",
                        },
                        {
                            id: "",
                            student_name: "Nayra Sharma",
                            email_id: "",
                            contact_number: "34567436654",
                            gender: "Feamle",
                            admission_year: "2022",
                            merit_diploma: "79",
                        },
                    ],
                },

                // <---------------------------------------------------------------third year---------------------------------------------------------------------->

                {
                    year: "Third",
                    year_head: "Purvi Tandel",
                    student_data: [
                        {
                            id: "2020_1",
                            student_name: "Pinal Nakarani",
                            email_id: "pinal@gmail.com",
                            contact_number: "9879870025",
                            gender: "Female",
                            admission_year: "2020",
                            merit_12th: "95",
                        },
                        {
                            id: "2020_2",
                            student_name: "Chandra Vakani",
                            email_id: "chandra@gmail.com",
                            contact_number: "9879870026",
                            gender: "Male",
                            admission_year: "2020",
                            merit_12th: "88",
                        },
                        {
                            id: "2020_3",
                            student_name: "Vishwas Rav",
                            email_id: "vr@gmail.com",
                            contact_number: "9879870027",
                            gender: "Male",
                            admission_year: "2020",
                            merit_12th: "78",
                        },
                        {
                            id: "2020_4",
                            student_name: "Arvi Khote",
                            email_id: "ak@gmail.com",
                            contact_number: "9879870028",
                            gender: "Female",
                            admission_year: "2020",
                            merit_12th: "88",
                        },
                        {
                            id: "2021_0_1",
                            student_name: "banshi pande",
                            email_id: "banshi_pande@gmail.com",
                            contact_number: "9879870017",
                            gender: "Female",
                            admission_year: "2021",
                            merit_diploma: "81",
                        },
                        {
                            id: "2021_0_3",
                            student_name: "shakshi pande",
                            email_id: "shakshi_pande@gmail.com",
                            contact_number: "34567436654",
                            gender: "Female",
                            admission_year: "2021",
                            merit_diploma: "83",
                        },
                        {
                            id: "",
                            student_name: "Smit Kikani",
                            email_id: "",
                            contact_number: "78351564545",
                            gender: "Male",
                            admission_year: "2021",
                            merit_diploma: "79",
                        },
                        {
                            id: "",
                            student_name: "Divy Patel",
                            email_id: "",
                            contact_number: "56536253545",
                            gender: "Male",
                            admission_year: "2020",
                            merit_12th: "79",
                        },
                        {
                            id: "",
                            student_name: "Yash Undhad",
                            email_id: "",
                            contact_number: "4747558555",
                            gender: "Female",
                            admission_year: "2021",
                            merit_diploma: "79",
                        },
                        {
                            id: "",
                            student_name: "Mayank Mardiya",
                            email_id: "",
                            contact_number: "9879870017",
                            gender: "Male",
                            admission_year: "2020",
                            merit_12th: "79",
                        },
                    ],
                },
                // <------------------------------------------------------------forth year----------------------------------------------------------------------->
                {
                    year: "Fourth",
                    year_head: "Akash Mehata",
                    student_data: [
                        {
                            id: "2019_1",
                            student_name: "Rahul Patel",
                            email_id: "rp@gmail.com",
                            contact_number: "9879870029",
                            gender: "Male",
                            admission_year: "2019",
                            merit_12th: "66",
                        },
                        {
                            id: "2019_2",
                            student_name: "Ravindra Dhudhat",
                            email_id: "rd@gmail.com",
                            contact_number: "9879870030",
                            gender: "Male",
                            admission_year: "2019",
                            merit_12th: "81",
                        },
                        {
                            id: "2019_4",
                            student_name: "Sanket Dravid",
                            email_id: "sanket@gmail.com",
                            contact_number: "34567436654",
                            gender: "Male",
                            admission_year: "2019",
                            merit_12th: "91",
                        },
                        {
                            id: "2019_7",
                            student_name: "Shree Vekariya",
                            email_id: "shree@gmail.com",
                            contact_number: "9879870032",
                            gender: "Female",
                            admission_year: "2019",
                            merit_12th: "78",
                        },
                        {
                            id: "",
                            student_name: "Shivam Dravid",
                            email_id: "",
                            contact_number: "77567478645",
                            gender: "Male",
                            admission_year: "2019",
                            merit_12th: "92",
                        },
                    ],
                },

                // <---------------------------------------------------------------pass out---------------------------------------------------------------------->

                {
                    year: "Pass Out",
                    year_head: "Akash Mehata",
                    student_data: [
                        {
                            id: "2018_1",
                            student_name: "Anshu Patel",
                            email_id: "anshu@gmail.com",
                            contact_number: "9879870037",
                            gender: "Male",
                            admission_year: "2018",
                            merit_12th: "76",
                        },
                        {
                            id: "2018_2",
                            student_name: "Latika Devani",
                            email_id: "ld@gmail.com",
                            contact_number: "9879870038",
                            gender: "Female",
                            admission_year: "2018",
                            merit_12th: "81",
                        },
                        {
                            id: "2018_7",
                            student_name: "Shekhar Shah",
                            email_id: "ss@gmail.com",
                            contact_number: "9879870039",
                            gender: "Male",
                            admission_year: "2018",
                            merit_12th: "91",
                        },
                        {
                            id: "2018_4",
                            student_name: "Pratik Vekariya",
                            email_id: "pratik@gmail.com",
                            contact_number: "34567436654",
                            gender: "Male",
                            admission_year: "2018",
                            merit_12th: "78",
                        },
                        {
                            id: "2018_5",
                            student_name: "shakshi pande",
                            email_id: "shakshi_pande@gmail.com",
                            contact_number: "92798734011",
                            gender: "Female",
                            admission_year: "2018",
                            merit_12th: "83",
                        },
                        {
                            id: "",
                            student_name: "Harsh Thoriya",
                            email_id: "",
                            contact_number: "5465432353652",
                            gender: "Male",
                            admission_year: "2019",
                            merit_diploma: "89",
                        },
                        {
                            id: "",
                            student_name: "Riya Nakrani",
                            email_id: "",
                            contact_number: "56787864553",
                            gender: "Female",
                            admission_year: "2019",
                            merit_diploma: "97",
                        },
                        {
                            id: "",
                            student_name: "Dushyant Vaja",
                            email_id: "",
                            contact_number: "5646456786354",
                            gender: "Male",
                            admission_year: "2019",
                            merit_diploma: "96",
                        },
                    ],
                },
            ],
        },

        // <------------------------------------------------------------------civil---------------------------------------------------------------->

        {
            department: "Civil",
            dep_head: "Virat Kohli",
            year: [
                {
                    year: "First",
                    year_head: "Nikhil Patel",
                    student_data: [
                        {
                            id: "",
                            student_name: "Harsh Patel",
                            email_id: "",
                            contact_number: "9879870001",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "79",
                        },
                        {
                            id: "",
                            student_name: "Jaimin Patel",
                            email_id: "",
                            contact_number: "9879870001",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "96",
                        },
                        {
                            id: "",
                            student_name: "Jeet Vasava",
                            email_id: "",
                            contact_number: "9879870001",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "81",
                        },
                        {
                            id: "2022_2",
                            student_name: "Shalini Patel",
                            email_id: "pshalini@gmail.com",
                            contact_number: "56787864553",
                            gender: "Female",
                            admission_year: "2022",
                            merit_12th: "85",
                        },
                        {
                            id: "2022_3",
                            student_name: "Kevin jadeja",
                            email_id: "kevin@gmail.com",
                            contact_number: "9879870003",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "87",
                        },
                        {
                            id: "2022_4",
                            student_name: "Harsh Dhorajiya",
                            email_id: "Harsh22@gmail.com",
                            contact_number: "9879870004",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "83",
                        },
                        {
                            id: "",
                            student_name: "Vishal Gajera",
                            email_id: "",
                            contact_number: "9835540004",
                            gender: "Male",
                            admission_year: "2022",
                            merit_12th: "93",
                        },
                    ],
                },

                // <-------------------------------------------------------------second year---------------------------------------------------------->

                {
                    year: "Second",
                    year_head: "Jagdish Vasava",
                    student_data: [
                        {
                            id: "",
                            student_name: "Jatin Panchal",
                            email_id: "",
                            contact_number: "9879870006",
                            gender: "Male",
                            admission_year: "2022",
                            merit_diploma: "57",
                        },
                        {
                            id: "",
                            student_name: "Kishan Vasani",
                            email_id: "",
                            contact_number: "56787864553",
                            gender: "Male",
                            admission_year: "2022",
                            merit_diploma: "68",
                        },
                        {
                            id: "2021_1",
                            student_name: "Divayesh Ranpara",
                            email_id: "dr@gmail.com",
                            contact_number: "9879870005",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "78",
                        },
                        {
                            id: "",
                            student_name: "Yagnik Devani",
                            email_id: "",
                            contact_number: "9879870008",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "88",
                        }, {
                            id: "",
                            student_name: "Ronak Koladiya",
                            email_id: "",
                            contact_number: "9879870008",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "80",
                        },
                        {
                            id: "2022_0_2",
                            student_name: "Krunal Mehata",
                            email_id: "Krunal23@gmail.com",
                            contact_number: "9879870006",
                            gender: "Male",
                            admission_year: "2022",
                            merit_diploma: "88",
                        },
                        {
                            id: "2022_0_4",
                            student_name: "Shubham Khunt",
                            email_id: "shubhu7@gmail.com",
                            contact_number: "9879870007",
                            gender: "Male",
                            admission_year: "2022",
                            merit_diploma: "67",
                        },
                        {
                            id: "",
                            student_name: "Bhargav Gajera",
                            email_id: "",
                            contact_number: "9835540004",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "93",
                        },
                        {
                            id: "2021_2",
                            student_name: "Ashwin Patel",
                            email_id: "apatel@gmail.com",
                            contact_number: "9879870008",
                            gender: "Male",
                            admission_year: "2021",
                            merit_12th: "77",
                        },
                    ],
                },

                // <-------------------------------------------------------------third year----------------------------------------------------------->

                {
                    year: "Third",
                    year_head: "Bharat Parmar",
                    student_data: [
                        {
                            id: "2021_0_1",
                            student_name: "Chitranjan Rama",
                            email_id: "c.r@gmail.com",
                            contact_number: "56787864553",
                            gender: "Male",
                            admission_year: "2021",
                            merit_diploma: "72",
                        },
                        {
                            id: "2020_2",
                            student_name: "Nupur Parmer",
                            email_id: "np@gmail.com",
                            contact_number: "9879870010",
                            gender: "Female",
                            admission_year: "2020",
                            merit_12th: "77",
                        },
                        {
                            id: "2020_3",
                            student_name: "Sameera Rai",
                            email_id: "sameera@gmail.com",
                            contact_number: "9879870011",
                            gender: "Female",
                            admission_year: "2020",
                            merit_12th: "88",
                        },
                        {
                            id: "2020_4",
                            student_name: "Prabhat Goda",
                            email_id: "pg@gmail.com",
                            contact_number: "9879870012",
                            gender: "Male",
                            admission_year: "2020",
                            merit_12th: "65",
                        },
                        {
                            id: "2021_0_2",
                            student_name: "Vaishali Bhatt",
                            email_id: "Vaishali_bhatt@gmail.com",
                            contact_number: "98798734011",
                            gender: "Female",
                            admission_year: "2021",
                            merit_diploma: "74",
                        },
                        {
                            id: "",
                            student_name: "Mitesh Dudhat",
                            email_id: "",
                            contact_number: "56787864553",
                            gender: "Male",
                            admission_year: "2020",
                            merit_12th: "93",
                        },
                        {
                            id: "",
                            student_name: "Pinal Patel",
                            email_id: "",
                            contact_number: "9978021537",
                            gender: "Female",
                            admission_year: "2021",
                            merit_diploma: "93",
                        },
                    ],
                },

                // <--------------------------------------------------------------fourth Year---------------------------------------------------------->

                {
                    year: "Fourth",
                    year_head: "Himanshu Shah",
                    student_data: [
                        {
                            id: "2019_1",
                            student_name: "Nancy Patel",
                            email_id: "nancy@gmail.com",
                            contact_number: "9879870013",
                            gender: "Female",
                            admission_year: "2019",
                            merit_12th: "77",
                        },
                        {
                            id: "2019_2",
                            student_name: "Sankalp Desai",
                            email_id: "sankalp",
                            contact_number: "9879870014",
                            gender: "Male",
                            admission_year: "2019",
                            merit_12th: "75",
                        },
                        {
                            id: "2019_3",
                            student_name: "Sudheer Chouhan",
                            email_id: "sc@gmail.com",
                            contact_number: "9879870015",
                            gender: "Male",
                            admission_year: "2019",
                            merit_12th: "57",
                        },
                        {
                            id: "2019_4",
                            student_name: "Niyati Chawada",
                            email_id: "niyati@gmail.com",
                            contact_number: "9879870016",
                            gender: "Female",
                            admission_year: "2019",
                            merit_12th: "89",
                        },
                        {
                            id: "",
                            student_name: "Megha Chawada",
                            email_id: "",
                            contact_number: "56787864553",
                            gender: "Female",
                            admission_year: "2020",
                            merit_diploma: "90",
                        },
                        {
                            id: "",
                            student_name: "Jyoti Chavda",
                            email_id: '',
                            contact_number: "9889870016",
                            gender: "Female",
                            admission_year: "2019",
                            merit_12th: "79",
                        },
                    ],
                },

                // <--------------------------------------------------------------pass year------------------------------------------------------------>

                {
                    year: "Pass Out",
                    year_head: "Dipak Jadeja",
                    student_data: [
                        {
                            id: "2018_1",
                            student_name: "Rutu Patel",
                            email_id: "rutu@gmail.com",
                            contact_number: "9879870033",
                            gender: "Female",
                            admission_year: "2018",
                            merit_12th: "68",
                        },
                        {
                            id: "2018_2",
                            student_name: "Charmi Dhudhat",
                            email_id: "charmi@gmail.com",
                            contact_number: "9879870034",
                            gender: "Female",
                            admission_year: "2018",
                            merit_12th: "87",
                        },
                        {
                            id: "2018_3",
                            student_name: "Savi Dravid",
                            email_id: "savi@gmail.com",
                            contact_number: "56787864553",
                            gender: "Feamle",
                            admission_year: "2018",
                            merit_12th: "91",
                        },
                        {
                            id: "2018_4",
                            student_name: "Savi patel",
                            email_id: "savi_patel@gmail.com",
                            contact_number: "98723470035",
                            gender: "Feamle",
                            admission_year: "2018",
                            merit_12th: "80",
                        },
                        {
                            id: "2018_5",
                            student_name: "raxita vaghasiya",
                            email_id: "raxita_vaghasiya@gmail.com",
                            contact_number: "987343470035",
                            gender: "Feamle",
                            admission_year: "2018",
                            merit_12th: "86",
                        },
                        {
                            id: "",
                            student_name: "Dhyey Sharma",
                            email_id: "",
                            contact_number: "8141652472",
                            gender: "Male",
                            admission_year: "2018",
                            merit_12th: "85",
                        },
                        {
                            id: "",
                            student_name: "Shrushti Miyani",
                            email_id: "",
                            contact_number: "8141652472",
                            gender: "Feamle",
                            admission_year: "2018",
                            merit_12th: "86",
                        },
                        {
                            id: "",
                            student_name: "Darshan chopda",
                            email_id: "",
                            contact_number: "8148652472",
                            gender: "Male",
                            admission_year: "2018",
                            merit_12th: "65",
                        },
                        {
                            id: "2018_6",
                            student_name: "Ishan Vekariya",
                            email_id: "ishan@gmail.com",
                            contact_number: "9879870036",
                            gender: "Male",
                            admission_year: "2018",
                            merit_12th: "78",
                        },
                    ],
                },
            ],
        },
    ],
};